apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: kafka-to-s3
spec:
  integration:
    configuration:
    - type: "secret"
      value: "aws-s3-secret"
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-source
    properties:
      bootstrapServers: "my-cluster-kafka-bootstrap:9092"
      topic: "application-log"
      securityProtocol: PLAINTEXT
      user: "test"
      password: "test"
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-s3-sink
    properties:
      bucketNameOrArn: "logging-to-kafka-to-s3"
      region: "ap-northeast-1"
