apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: kafka-to-kinesis
spec:
  integration:
    configuration:
    - type: "secret"
      value: "aws-s3-secret"
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-source
    properties:
      bootstrapServers: "my-cluster-kafka-bootstrap:9092"
      topic: "application-log"
      securityProtocol: PLAINTEXT
      user: "test"
      password: "test"
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-kinesis-sink
    properties:
      region: "ap-northeast-1"
      stream: "logging-to-kinesis-dummy"
  errorHandler:
    dead-letter-channel:
      endpoint:
        ref:
          kind: Kamelet
          apiVersion: camel.apache.org/v1alpha1
          name: kafka-sink
        properties:
          bootstrapServers: "my-cluster-kafka-bootstrap:9092"
          topic: "dead-letter-channel"
          securityProtocol: PLAINTEXT
          user: "test"
          password: "test"
      parameters:
        maximumRedeliveries: 1
