apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: my-kafka-source
  annotations:
    camel.apache.org/catalog.version: 1.8.0.redhat-00090
    camel.apache.org/kamelet.group: Kafka
    camel.apache.org/kamelet.icon: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOS4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9IjAgMCA1MDAgNTAwIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCA1MDAgNTAwOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+DQo8ZyBpZD0iWE1MSURfMV8iPg0KCTxwYXRoIGlkPSJYTUxJRF85XyIgZD0iTTMxNC44LDI2OS43Yy0xNC4yLDAtMjcsNi4zLTM1LjcsMTYuMkwyNTYuOCwyNzBjMi40LTYuNSwzLjctMTMuNiwzLjctMjAuOWMwLTcuMi0xLjMtMTQuMS0zLjYtMjAuNg0KCQlsMjIuMy0xNS43YzguNyw5LjksMjEuNCwxNi4xLDM1LjYsMTYuMWMyNi4yLDAsNDcuNi0yMS4zLDQ3LjYtNDcuNnMtMjEuMy00Ny42LTQ3LjYtNDcuNnMtNDcuNiwyMS4zLTQ3LjYsNDcuNg0KCQljMCw0LjcsMC43LDkuMiwyLDEzLjVsLTIyLjMsMTUuN2MtOS4zLTExLjYtMjIuOC0xOS42LTM4LjEtMjIuMXYtMjYuOWMyMS42LTQuNSwzNy44LTIzLjcsMzcuOC00Ni42YzAtMjYuMi0yMS4zLTQ3LjYtNDcuNi00Ny42DQoJCWMtMjYuMiwwLTQ3LjYsMjEuMy00Ny42LDQ3LjZjMCwyMi42LDE1LjgsNDEuNSwzNi45LDQ2LjN2MjcuM2MtMjguOCw1LjEtNTAuOCwzMC4yLTUwLjgsNjAuNWMwLDMwLjQsMjIuMiw1NS43LDUxLjIsNjAuNXYyOC44DQoJCWMtMjEuMyw0LjctMzcuNCwyMy43LTM3LjQsNDYuNGMwLDI2LjIsMjEuMyw0Ny42LDQ3LjYsNDcuNmMyNi4yLDAsNDcuNi0yMS4zLDQ3LjYtNDcuNmMwLTIyLjctMTYtNDEuOC0zNy40LTQ2LjR2LTI4LjgNCgkJYzE1LTIuNSwyOC4yLTEwLjQsMzcuNC0yMS44bDIyLjUsMTUuOWMtMS4yLDQuMy0xLjksOC43LTEuOSwxMy40YzAsMjYuMiwyMS4zLDQ3LjYsNDcuNiw0Ny42czQ3LjYtMjEuMyw0Ny42LTQ3LjYNCgkJQzM2Mi40LDI5MSwzNDEuMSwyNjkuNywzMTQuOCwyNjkuN3ogTTMxNC44LDE1OC40YzEyLjcsMCwyMy4xLDEwLjQsMjMuMSwyMy4xYzAsMTIuNy0xMC4zLDIzLjEtMjMuMSwyMy4xcy0yMy4xLTEwLjQtMjMuMS0yMy4xDQoJCUMyOTEuOCwxNjguOCwzMDIuMSwxNTguNCwzMTQuOCwxNTguNHogTTE3NiwxMTUuMWMwLTEyLjcsMTAuMy0yMy4xLDIzLjEtMjMuMWMxMi43LDAsMjMuMSwxMC40LDIzLjEsMjMuMQ0KCQljMCwxMi43LTEwLjMsMjMuMS0yMy4xLDIzLjFDMTg2LjMsMTM4LjIsMTc2LDEyNy44LDE3NiwxMTUuMXogTTIyMi4xLDM4NC45YzAsMTIuNy0xMC4zLDIzLjEtMjMuMSwyMy4xDQoJCWMtMTIuNywwLTIzLjEtMTAuNC0yMy4xLTIzLjFjMC0xMi43LDEwLjMtMjMuMSwyMy4xLTIzLjFDMjExLjgsMzYxLjgsMjIyLjEsMzcyLjIsMjIyLjEsMzg0Ljl6IE0xOTkuMSwyODEuMw0KCQljLTE3LjcsMC0zMi4yLTE0LjQtMzIuMi0zMi4yYzAtMTcuNywxNC40LTMyLjIsMzIuMi0zMi4yYzE3LjcsMCwzMi4yLDE0LjQsMzIuMiwzMi4yQzIzMS4yLDI2Ni45LDIxNi44LDI4MS4zLDE5OS4xLDI4MS4zeg0KCQkgTTMxNC44LDM0MC4zYy0xMi43LDAtMjMuMS0xMC40LTIzLjEtMjMuMWMwLTEyLjcsMTAuMy0yMy4xLDIzLjEtMjMuMXMyMy4xLDEwLjQsMjMuMSwyMy4xQzMzNy45LDMzMCwzMjcuNSwzNDAuMywzMTQuOCwzNDAuM3oiLz4NCjwvZz4NCjwvc3ZnPg0K
    camel.apache.org/provider: Red Hat
  labels:
    camel.apache.org/kamelet.type: source
spec:
  definition:
    description: Receive data from Kafka topics.
    properties:
      allowManualCommit:
        default: false
        description: Whether to allow doing manual commits
        title: Allow Manual Commit
        type: boolean
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:checkbox
      autoCommitEnable:
        default: true
        description: If true, periodically commit to ZooKeeper the offset of messages already fetched by the consumer
        title: Auto Commit Enable
        type: boolean
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:checkbox
      autoOffsetReset:
        default: latest
        description: What to do when there is no initial offset. There are 3 enums and the value can be one of latest, earliest, none
        title: Auto Offset Reset
        type: string
      bootstrapServers:
        description: Comma separated list of Kafka Broker URLs
        title: Brokers
        type: string
      deserializeHeaders:
        default: false
        description: When enabled the Kamelet source will deserialize all message headers to String representation.
        title: Automatically Deserialize Headers
        type: boolean
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:checkbox
      password:
        description: Password to authenticate to kafka
        format: password
        title: Password
        type: string
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
        - urn:camel:group:credentials
      pollOnError:
        default: ERROR_HANDLER
        description: What to do if kafka threw an exception while polling for new messages. There are 5 enums and the value can be one of DISCARD, ERROR_HANDLER, RECONNECT, RETRY, STOP
        title: Poll On Error Behavior
        type: string
      saslMechanism:
        default: PLAIN
        description: The Simple Authentication and Security Layer (SASL) Mechanism used.
        title: SASL Mechanism
        type: string
      securityProtocol:
        default: SASL_SSL
        description: Protocol used to communicate with brokers. SASL_PLAINTEXT, PLAINTEXT, SASL_SSL and SSL are supported
        title: Security Protocol
        type: string
      topic:
        description: Comma separated list of Kafka topic names
        title: Topic Names
        type: string
      user:
        description: Username to authenticate to Kafka
        title: Username
        type: string
      consumerGroup:
        title: Consumer Group
        description: A string that uniquely identifies the group of consumers to which this source belongs
        type: string
        example: "my-group-id"
      consumersCount:
        title: Consumers Count
        description: The number of consumers that connect to kafka server. Each consumer is run on a separate thread, that retrieves and process the incoming data.
        type: integer
        default: 1
    required:
    - topic
    - bootstrapServers
    - user
    - password
    title: My Kafka Source
    type: object
  dependencies:
  - mvn:org.apache.camel.kamelets:camel-kamelets-utils:1.8.0.redhat-00090
  - camel:core
  - camel:kafka
  - camel:kamelet
  template:
    from:
      parameters:
        allowManualCommit: '{{allowManualCommit}}'
        autoCommitEnable: '{{autoCommitEnable}}'
        autoOffsetReset: '{{autoOffsetReset}}'
        brokers: '{{?bootstrapServers}}'
        pollOnError: '{{pollOnError}}'
        saslJaasConfig: org.apache.kafka.common.security.plain.PlainLoginModule required username='{{user}}' password='{{password}}';
        saslMechanism: '{{saslMechanism}}'
        securityProtocol: '{{securityProtocol}}'
        groupId: "{{?consumerGroup}}"
        consumersCount: "{{consumersCount}}"
      steps:
      - set-property:
          constant: '{{deserializeHeaders}}'
          name: deserializeHeaders
      - choice:
          when:
          - simple: ${exchangeProperty.deserializeHeaders} == 'true'
            steps:
            - bean: org.apache.camel.kamelets.utils.serialization.kafka.KafkaHeaderDeserializer
      - to: kamelet:sink
      uri: kafka:{{topic}}
